"""
BD Playbook Generator Engine
Creates comprehensive sales playbooks for Hot-tier opportunities (score >= 80).

Based on: contact-classification-skill.md and program-mapping-skill.md

Generates 5 sections:
1. Program Intel - Program background, contract details, recent news
2. Org Intel - Key contacts, org chart, decision makers
3. Pain Points - Staffing challenges, capability gaps, timeline pressures
4. Competitive Landscape - Incumbent, competitors, win themes
5. Action Plan - Next steps, outreach sequence, talking points

Output formats:
- Intro Email - Personalized outreach email
- Call Script - Phone conversation guide
- Talking Points - Key discussion topics
- Full Playbook - Complete briefing document (Markdown)
"""

import json
import sys
from datetime import datetime
from pathlib import Path
from typing import Dict, List, Any
from dataclasses import dataclass, field

# Add parent directories for imports
sys.path.insert(0, str(Path(__file__).parent.parent.parent))

try:
    from Engine3_OrgChart.scripts.contact_lookup import (
        lookup_contacts,
        format_contacts_json,
    )

    HAS_CONTACT_LOOKUP = True
except ImportError:
    HAS_CONTACT_LOOKUP = False


# ============================================
# DATA CLASSES
# ============================================


@dataclass
class PlaybookData:
    """Data container for playbook generation."""

    # Core opportunity info
    job_title: str
    company: str
    location: str
    clearance: str
    description: str = ""

    # Program mapping data
    program_name: str = ""
    agency: str = ""
    prime_contractor: str = ""
    match_confidence: float = 0.0
    match_type: str = "inferred"
    match_signals: List[str] = field(default_factory=list)

    # Scoring data
    bd_score: int = 0
    priority_tier: str = "Warm"
    score_breakdown: Dict[str, Any] = field(default_factory=dict)
    recommendations: List[str] = field(default_factory=list)

    # Contact data
    contacts: List[Dict] = field(default_factory=list)
    key_decision_makers: List[Dict] = field(default_factory=list)

    # Intelligence data
    technologies: List[str] = field(default_factory=list)
    certifications: List[str] = field(default_factory=list)
    pain_points: List[str] = field(default_factory=list)

    # Metadata
    source_url: str = ""
    date_posted: str = ""
    scraped_at: str = ""


@dataclass
class PlaybookOutput:
    """Container for generated playbook outputs."""

    full_playbook: str
    intro_email: str
    call_script: str
    talking_points: str
    data: PlaybookData
    generated_at: str
    output_paths: Dict[str, str] = field(default_factory=dict)


# ============================================
# TEMPLATES
# ============================================

FULL_PLAYBOOK_TEMPLATE = """# BD Playbook: {job_title}
## {program_name} Opportunity

**Generated:** {generated_date}
**Priority:** {priority_tier_emoji} {priority_tier} (Score: {bd_score}/100)
**Match Confidence:** {match_confidence}% ({match_type})

---

## 1. Program Intel

### Program Overview
**Program:** {program_name}
**Customer Agency:** {agency}
**Prime Contractor:** {prime_contractor}
**Location:** {location}

### Opportunity Details
**Position:** {job_title}
**Clearance Required:** {clearance}
**Company:** {company}

### Match Signals
{match_signals_list}

### Job Description
{description}

---

## 2. Org Intel

### Key Contacts
{contacts_section}

### Decision Makers
{decision_makers_section}

---

## 3. Pain Points & Opportunities

### Identified Pain Points
{pain_points_section}

### Staffing Signals
- **Clearance Level:** {clearance} (indicates {clearance_insight})
- **Location:** {location} (market conditions: {location_insight})
- **Technologies:** {technologies_list}

### Certification Requirements
{certifications_list}

---

## 4. Competitive Landscape

### Current Landscape
**Prime Contractor:** {prime_contractor}
**Our Position:** {our_position}

### Win Themes
{win_themes}

### Competitive Differentiators
{differentiators}

---

## 5. Action Plan

### Immediate Actions
{action_items}

### Recommended Outreach Sequence
{outreach_sequence}

### BD Recommendations
{recommendations_list}

---

## Source Information

**Job URL:** {source_url}
**Date Posted:** {date_posted}
**Scraped:** {scraped_at}

---

*Generated by BD Automation Engine - Engine4_Playbook v1.0*
"""

INTRO_EMAIL_TEMPLATE = """Subject: {program_name} Opportunity - {job_title} Position

Hi [Contact Name],

I noticed {company} is looking for a {job_title} supporting the {program_name} program in {location}.

{company_intro}

Given your role with {prime_contractor}, I wanted to reach out to explore potential collaboration opportunities. Our team has {relevant_experience}.

{value_proposition}

Would you have 15 minutes this week for a brief call to discuss how we might support your {program_name} staffing needs?

Best regards,
[Your Name]
[Your Title]
[Your Company]

---
*BD Score: {bd_score}/100 | Priority: {priority_tier}*
"""

CALL_SCRIPT_TEMPLATE = """# Call Script: {job_title} - {program_name}

## Opening (30 seconds)
"Hi [Name], this is [Your Name] from [Company]. I'm reaching out about your {job_title} position for the {program_name} program. Is this a good time for a quick 5-minute call?"

## Hook (1 minute)
{hook_statement}

## Discovery Questions
1. "What's your current timeline for filling this {job_title} role?"
2. "Are you working with {prime_contractor} directly or through a sub?"
3. "What are the biggest challenges you're facing with {program_name} staffing?"
4. "Is the {clearance} clearance requirement firm, or is there flexibility?"

## Value Proposition (2 minutes)
{value_proposition}

## Key Talking Points
{talking_points_list}

## Pain Point Questions
{pain_point_questions}

## Close
"Based on what you've shared, I think we could be a strong fit for your {program_name} needs. Can we schedule a follow-up call to discuss specific candidates/capabilities?"

## Objection Handling
{objection_handling}

---
*BD Score: {bd_score}/100 | Match Confidence: {match_confidence}%*
"""

TALKING_POINTS_TEMPLATE = """# Talking Points: {job_title} - {program_name}

## Key Messages

### Program Knowledge
- {program_name} is a {agency} program
- Prime contractor: {prime_contractor}
- Location: {location}
- Clearance: {clearance}

### Our Strengths
{our_strengths}

### Pain Points to Address
{pain_points_talking}

### Competitive Positioning
{competitive_positioning}

### Questions to Ask
{discovery_questions}

### Next Steps to Propose
{next_steps}

---
*Priority: {priority_tier} | BD Score: {bd_score}/100*
"""


# ============================================
# EXTRACTION FUNCTIONS
# ============================================


def extract_playbook_data(job: Dict[str, Any]) -> PlaybookData:
    """Extract playbook data from enriched job dictionary."""
    mapping = job.get("_mapping", {})
    scoring = job.get("_scoring", {})

    # Extract technologies from job data
    technologies = job.get("Technologies", [])
    if isinstance(technologies, str):
        technologies = [t.strip() for t in technologies.split(",") if t.strip()]

    # Extract certifications
    certifications = job.get("Certifications Required", [])
    if isinstance(certifications, str):
        certifications = [c.strip() for c in certifications.split(",") if c.strip()]

    # Infer pain points from job signals
    pain_points = infer_pain_points(job)

    return PlaybookData(
        job_title=job.get("Job Title/Position", job.get("title", "Unknown Position")),
        company=job.get("Prime Contractor", job.get("company", "Unknown Company")),
        location=job.get("Location", job.get("location", "Unknown Location")),
        clearance=job.get("Security Clearance", job.get("clearance", "Not specified")),
        description=job.get("Position Overview", job.get("description", ""))[:2000],
        program_name=mapping.get(
            "program_name", job.get("Matched Program", "Unmatched")
        ),
        agency=mapping.get("agency", infer_agency(mapping.get("program_name", ""))),
        prime_contractor=mapping.get(
            "prime_contractor", job.get("Prime Contractor", "")
        ),
        match_confidence=mapping.get("match_confidence", 0.5),
        match_type=mapping.get("match_type", "inferred"),
        match_signals=mapping.get("signals", job.get("Match Signals", [])),
        bd_score=scoring.get("BD Priority Score", job.get("BD Priority Score", 50)),
        priority_tier=scoring.get("Priority Tier", job.get("Priority Tier", "Warm"))
        .replace("🔥", "")
        .replace("🟡", "")
        .replace("❄️", "")
        .strip(),
        score_breakdown=scoring.get("Score Breakdown", {}),
        recommendations=scoring.get("Recommendations", []),
        technologies=technologies,
        certifications=certifications,
        pain_points=pain_points,
        source_url=job.get("Source URL", job.get("url", "")),
        date_posted=job.get("Date Posted", job.get("date", "")),
        scraped_at=job.get("Scraped At", ""),
    )


def infer_agency(program_name: str) -> str:
    """Infer agency from program name."""
    program_upper = program_name.upper()

    if "DCGS" in program_upper:
        if "AF" in program_upper or "AIR FORCE" in program_upper:
            return "US Air Force"
        if "ARMY" in program_upper or "DCGS-A" in program_upper:
            return "US Army"
        if "NAVY" in program_upper or "DCGS-N" in program_upper:
            return "US Navy"
        return "DoD - DCGS"

    if "NSA" in program_upper or "SIGINT" in program_upper:
        return "NSA"
    if "NGA" in program_upper or "GEOINT" in program_upper:
        return "NGA"
    if "NRO" in program_upper:
        return "NRO"
    if "DIA" in program_upper:
        return "DIA"
    if "CIA" in program_upper:
        return "CIA"
    if "SOCOM" in program_upper:
        return "USSOCOM"
    if "SPACE" in program_upper:
        return "US Space Force"

    return "DoD/IC"


def infer_pain_points(job: Dict[str, Any]) -> List[str]:
    """Infer pain points from job data."""
    pain_points = []

    clearance = job.get("Security Clearance", "").upper()
    location = job.get("Location", "")
    description = job.get("Position Overview", job.get("description", "")).lower()

    # Clearance-based pain points
    if "POLY" in clearance:
        pain_points.append(
            "High clearance requirement limits candidate pool significantly"
        )
    if "TS/SCI" in clearance:
        pain_points.append("TS/SCI requirement reduces available talent by ~90%")

    # Location-based pain points
    if "San Diego" in location:
        pain_points.append("San Diego is understaffed for DCGS - critical hiring need")
    if "Remote" in location:
        pain_points.append("Remote position indicates flexibility in hiring approach")

    # Description-based pain points
    if "urgent" in description or "immediate" in description:
        pain_points.append("Urgent hiring need - timeline pressure")
    if "backfill" in description or "replacement" in description:
        pain_points.append("Backfill position - critical gap to fill")
    if "growth" in description or "expansion" in description:
        pain_points.append("Program growth - potential for multiple positions")

    if not pain_points:
        pain_points.append("Standard staffing need - competitive market")

    return pain_points


def get_clearance_insight(clearance: str) -> str:
    """Get insight about clearance level."""
    clearance_upper = clearance.upper()

    if "POLY" in clearance_upper:
        return "highest-value position, very limited candidate pool"
    if "TS/SCI" in clearance_upper:
        return "high-value cleared position, competitive market"
    if "TOP SECRET" in clearance_upper or "TS" in clearance_upper:
        return "significant clearance requirement, moderately competitive"
    if "SECRET" in clearance_upper:
        return "standard DoD clearance, larger candidate pool"

    return "clearance requirements may vary"


def get_location_insight(location: str) -> str:
    """Get insight about location market."""
    location_lower = location.lower()

    if "san diego" in location_lower:
        return "understaffed DCGS site, high demand"
    if "hampton" in location_lower or "langley" in location_lower:
        return "competitive ISR market, established presence"
    if "fort meade" in location_lower:
        return "NSA hub, extremely competitive for cleared talent"
    if "colorado springs" in location_lower:
        return "Space Force/MDA growth area"
    if "remote" in location_lower:
        return "flexible location, wider candidate access"
    if "dc" in location_lower or "northern virginia" in location_lower:
        return "highly competitive DC metro market"

    return "regional market conditions apply"


# ============================================
# GENERATION FUNCTIONS
# ============================================


def generate_full_playbook(data: PlaybookData) -> str:
    """Generate complete playbook markdown."""

    # Format match signals
    if data.match_signals:
        match_signals_list = "\n".join(f"- {signal}" for signal in data.match_signals)
    else:
        match_signals_list = "- No specific signals identified"

    # Format contacts section
    if data.contacts:
        contacts_section = "\n".join(
            f"- **{c.get('name', 'Unknown')}** - {c.get('title', '')} ({c.get('tier', 'IC')})"
            for c in data.contacts[:5]
        )
    else:
        contacts_section = "No contacts found in database. Manual research recommended."

    # Format decision makers
    key_contacts = [c for c in data.contacts if c.get("tier", 6) <= 3]
    if key_contacts:
        decision_makers_section = "\n".join(
            f"- **{c.get('name', 'Unknown')}** - {c.get('title', '')} - Priority: {c.get('bd_priority', 'Medium')}"
            for c in key_contacts[:3]
        )
    else:
        decision_makers_section = (
            "No decision makers identified. Target Tier 1-3 contacts."
        )

    # Format pain points
    if data.pain_points:
        pain_points_section = "\n".join(f"- {point}" for point in data.pain_points)
    else:
        pain_points_section = "- No specific pain points identified"

    # Format technologies
    if data.technologies:
        technologies_list = ", ".join(data.technologies[:10])
    else:
        technologies_list = "Not specified"

    # Format certifications
    if data.certifications:
        certifications_list = "\n".join(f"- {cert}" for cert in data.certifications)
    else:
        certifications_list = "- No specific certifications required"

    # Format recommendations
    if data.recommendations:
        recommendations_list = "\n".join(f"- {rec}" for rec in data.recommendations)
    else:
        recommendations_list = "- Follow up based on priority tier\n- Research additional contacts\n- Prepare capability briefing"

    # Determine priority emoji
    tier_emoji = {
        "Hot": "🔥",
        "Warm": "🟡",
        "Cold": "❄️",
    }.get(data.priority_tier, "")

    # Win themes based on program
    win_themes = generate_win_themes(data)

    # Differentiators
    differentiators = generate_differentiators(data)

    # Action items
    action_items = generate_action_items(data)

    # Outreach sequence
    outreach_sequence = generate_outreach_sequence(data)

    # Our position assessment
    our_position = (
        "Potential subcontractor/teaming partner"
        if data.prime_contractor
        else "Direct bid opportunity"
    )

    return FULL_PLAYBOOK_TEMPLATE.format(
        job_title=data.job_title,
        program_name=data.program_name,
        generated_date=datetime.now().strftime("%Y-%m-%d %H:%M"),
        priority_tier=data.priority_tier,
        priority_tier_emoji=tier_emoji,
        bd_score=data.bd_score,
        match_confidence=int(data.match_confidence * 100),
        match_type=data.match_type,
        agency=data.agency or "DoD/IC",
        prime_contractor=data.prime_contractor or "Unknown",
        location=data.location,
        clearance=data.clearance or "Not specified",
        company=data.company,
        match_signals_list=match_signals_list,
        description=data.description[:1500]
        if data.description
        else "No description available.",
        contacts_section=contacts_section,
        decision_makers_section=decision_makers_section,
        pain_points_section=pain_points_section,
        clearance_insight=get_clearance_insight(data.clearance),
        location_insight=get_location_insight(data.location),
        technologies_list=technologies_list,
        certifications_list=certifications_list,
        our_position=our_position,
        win_themes=win_themes,
        differentiators=differentiators,
        action_items=action_items,
        outreach_sequence=outreach_sequence,
        recommendations_list=recommendations_list,
        source_url=data.source_url or "N/A",
        date_posted=data.date_posted or "N/A",
        scraped_at=data.scraped_at or "N/A",
    )


def generate_intro_email(data: PlaybookData) -> str:
    """Generate introduction email template."""

    company_intro = f"[Your Company] specializes in providing cleared technical talent to {data.agency or 'DoD/IC'} programs."

    relevant_experience = (
        f"deep experience supporting {data.program_name} and similar programs"
    )

    value_proposition = f"We have access to cleared candidates with the {data.clearance} clearance you require, and a track record of rapid fulfillment for {data.agency or 'DoD'} programs."

    return INTRO_EMAIL_TEMPLATE.format(
        program_name=data.program_name,
        job_title=data.job_title,
        company=data.company,
        location=data.location,
        prime_contractor=data.prime_contractor or data.company,
        company_intro=company_intro,
        relevant_experience=relevant_experience,
        value_proposition=value_proposition,
        bd_score=data.bd_score,
        priority_tier=data.priority_tier,
    )


def generate_call_script(data: PlaybookData) -> str:
    """Generate phone call script."""

    hook_statement = f"\"I've been tracking the {data.program_name} program and noticed you have some critical staffing needs, particularly for {data.clearance}-cleared talent in {data.location}. We've had success helping similar programs fill these hard-to-find positions.\""

    # Generate talking points list
    talking_points = [
        f"Our {data.clearance} cleared candidate pipeline",
        f"Past performance on {data.agency or 'DoD'} programs",
        f"Understanding of {data.program_name} requirements",
        "Rapid deployment capability",
    ]
    talking_points_list = "\n".join(f"- {point}" for point in talking_points)

    # Pain point questions
    pain_questions = [
        f'"What\'s been the biggest challenge filling {data.clearance} positions?"',
        '"Are you seeing any changes in program scope or budget?"',
        '"How is your current teaming arrangement working?"',
    ]
    pain_point_questions = "\n".join(f"- {q}" for q in pain_questions)

    # Value proposition
    value_proposition = f'"Our team has successfully supported multiple {data.agency or "DoD"} programs with similar requirements. We maintain an active pipeline of {data.clearance}-cleared professionals and can typically present qualified candidates within 2 weeks."'

    # Objection handling
    objections = [
        '"We\'re already working with vendors" → "Understood. Many of our clients use us as a complementary source, especially for hard-to-fill cleared positions. Would it be helpful to have a backup option?"',
        '"No budget" → "I hear that. When do you anticipate your next funding cycle? I\'d like to stay in touch for when needs arise."',
        '"Send me information" → "Happy to. What specific capabilities are most relevant to your current priorities?"',
    ]
    objection_handling = "\n".join(f"- {obj}" for obj in objections)

    return CALL_SCRIPT_TEMPLATE.format(
        job_title=data.job_title,
        program_name=data.program_name,
        prime_contractor=data.prime_contractor or data.company,
        clearance=data.clearance,
        hook_statement=hook_statement,
        value_proposition=value_proposition,
        talking_points_list=talking_points_list,
        pain_point_questions=pain_point_questions,
        objection_handling=objection_handling,
        bd_score=data.bd_score,
        match_confidence=int(data.match_confidence * 100),
    )


def generate_talking_points(data: PlaybookData) -> str:
    """Generate talking points document."""

    # Our strengths
    strengths = [
        f"Active pipeline of {data.clearance}-cleared candidates",
        f"Experience supporting {data.agency or 'DoD'} programs",
        "Rapid candidate deployment (typically 2-3 weeks)",
        "Strong retention rates on cleared programs",
    ]
    our_strengths = "\n".join(f"- {s}" for s in strengths)

    # Pain points to address
    if data.pain_points:
        pain_points_talking = "\n".join(
            f"- Address: {point}" for point in data.pain_points[:5]
        )
    else:
        pain_points_talking = (
            "- Explore staffing challenges\n- Identify timeline pressures"
        )

    # Competitive positioning
    competitive_positioning = f"""- Position against incumbent gaps
- Emphasize {data.clearance} pipeline strength
- Highlight {data.location} local presence/remote capabilities
- Differentiate on speed and quality"""

    # Discovery questions
    discovery_questions = f"""1. What's driving the current hiring need?
2. How many similar positions do you anticipate?
3. What's been your experience with current vendors?
4. Are there upcoming recompetes we should track?
5. Who else should we be talking to about {data.program_name}?"""

    # Next steps
    next_steps = f"""1. Schedule technical deep-dive call
2. Share relevant past performance
3. Present initial candidate slate
4. Propose teaming arrangement (if applicable)"""

    return TALKING_POINTS_TEMPLATE.format(
        job_title=data.job_title,
        program_name=data.program_name,
        agency=data.agency or "DoD/IC",
        prime_contractor=data.prime_contractor or "Unknown",
        location=data.location,
        clearance=data.clearance,
        our_strengths=our_strengths,
        pain_points_talking=pain_points_talking,
        competitive_positioning=competitive_positioning,
        discovery_questions=discovery_questions,
        next_steps=next_steps,
        priority_tier=data.priority_tier,
        bd_score=data.bd_score,
    )


def generate_win_themes(data: PlaybookData) -> str:
    """Generate win themes based on opportunity data."""
    themes = []

    if "TS/SCI" in data.clearance.upper() or "POLY" in data.clearance.upper():
        themes.append(
            "- **Cleared Talent Pipeline:** Emphasize active pool of high-clearance candidates"
        )

    if data.match_confidence >= 0.7:
        themes.append(
            f"- **Program Expertise:** Demonstrate deep understanding of {data.program_name}"
        )

    if data.pain_points:
        themes.append(
            "- **Pain Point Solutions:** Address identified staffing challenges directly"
        )

    if data.location:
        themes.append(
            f"- **Local Presence:** Highlight {data.location} capabilities or remote flexibility"
        )

    if not themes:
        themes = [
            "- **Technical Excellence:** Proven track record on similar programs",
            "- **Rapid Response:** Quick candidate turnaround",
            "- **Mission Focus:** Understanding of customer priorities",
        ]

    return "\n".join(themes)


def generate_differentiators(data: PlaybookData) -> str:
    """Generate competitive differentiators."""
    differentiators = [
        f"- Active {data.clearance} candidate pipeline (vs. starting from scratch)",
        f"- Past performance on {data.agency or 'DoD'} programs",
        "- Retention-focused approach (reduces customer risk)",
        "- Rapid deployment capability (2-3 week typical)",
    ]
    return "\n".join(differentiators)


def generate_action_items(data: PlaybookData) -> str:
    """Generate immediate action items."""
    actions = []

    if data.bd_score >= 80:
        actions.append(
            "1. **IMMEDIATE:** Reach out to identified contacts within 24 hours"
        )
        actions.append(f"2. Research {data.prime_contractor} BD/capture team contacts")
        actions.append(f"3. Prepare {data.program_name} capabilities one-pager")
    else:
        actions.append("1. Add to weekly follow-up queue")
        actions.append("2. Research additional contacts")
        actions.append("3. Monitor for priority changes")

    actions.append(f"4. Track {data.program_name} news and contract announcements")
    actions.append("5. Update CRM with opportunity details")

    return "\n".join(actions)


def generate_outreach_sequence(data: PlaybookData) -> str:
    """Generate recommended outreach sequence."""
    if data.bd_score >= 80:
        return """**Hot Priority Sequence:**
- Day 1: Send intro email to primary contact
- Day 2: LinkedIn connection request
- Day 3: Follow-up call (morning)
- Day 5: Second email with value-add content
- Day 7: Call attempt #2
- Day 10: Final email with specific ask"""
    elif data.bd_score >= 50:
        return """**Warm Priority Sequence:**
- Week 1: Intro email
- Week 2: Follow-up email with case study
- Week 3: Call attempt
- Week 4: Value-add content email"""
    else:
        return """**Pipeline Tracking:**
- Add to monthly newsletter
- Monitor for priority signals
- Re-evaluate quarterly"""


# ============================================
# MAIN GENERATION FUNCTION
# ============================================


def generate_playbook(
    job: Dict[str, Any], include_contacts: bool = True, output_formats: List[str] = None
) -> PlaybookOutput:
    """
    Generate complete playbook for an opportunity.

    Args:
        job: Enriched job dictionary with _mapping and _scoring data
        include_contacts: Whether to lookup contacts from database
        output_formats: List of formats to generate ['full', 'email', 'call', 'talking']

    Returns:
        PlaybookOutput with all generated materials
    """
    if output_formats is None:
        output_formats = ["full", "email", "call", "talking"]

    # Extract data
    data = extract_playbook_data(job)

    # Lookup contacts if available
    if include_contacts and HAS_CONTACT_LOOKUP:
        try:
            result = lookup_contacts(
                program_name=data.program_name,
                prime_contractor=data.prime_contractor or data.company,
            )
            data.contacts = format_contacts_json(result) if result else []
        except Exception:
            data.contacts = []

    # Generate outputs
    full_playbook = generate_full_playbook(data) if "full" in output_formats else ""
    intro_email = generate_intro_email(data) if "email" in output_formats else ""
    call_script = generate_call_script(data) if "call" in output_formats else ""
    talking_points = (
        generate_talking_points(data) if "talking" in output_formats else ""
    )

    return PlaybookOutput(
        full_playbook=full_playbook,
        intro_email=intro_email,
        call_script=call_script,
        talking_points=talking_points,
        data=data,
        generated_at=datetime.now().isoformat(),
    )


def generate_playbooks_batch(
    jobs: List[Dict[str, Any]],
    output_dir: str = "data/deliverables/briefings",
    min_score: int = 80,
    include_contacts: bool = True,
    output_formats: List[str] = None,
) -> List[PlaybookOutput]:
    """
    Generate playbooks for a batch of opportunities.

    Args:
        jobs: List of enriched job dictionaries
        output_dir: Directory to save playbook files
        min_score: Minimum BD score to generate playbook (default: 80 for Hot tier)
        include_contacts: Whether to lookup contacts
        output_formats: Formats to generate

    Returns:
        List of PlaybookOutput objects
    """
    if output_formats is None:
        output_formats = ["full", "email", "call", "talking"]

    # Create output directory
    Path(output_dir).mkdir(parents=True, exist_ok=True)

    results = []

    for job in jobs:
        # Get BD score
        score = job.get("_scoring", {}).get(
            "BD Priority Score", job.get("BD Priority Score", 50)
        )

        # Skip if below threshold
        if score < min_score:
            continue

        # Generate playbook
        output = generate_playbook(job, include_contacts, output_formats)

        # Save files
        title = output.data.job_title[:40]
        program = output.data.program_name[:30]
        safe = lambda s: "".join(c for c in s if c.isalnum() or c in " -_")
        base_name = f"{safe(program)}_{safe(title)}"

        output.output_paths = {}

        if output.full_playbook:
            path = Path(output_dir) / f"{base_name}_Playbook.md"
            with open(path, "w", encoding="utf-8") as f:
                f.write(output.full_playbook)
            output.output_paths["playbook"] = str(path)

        if output.intro_email:
            path = Path(output_dir) / f"{base_name}_Email.txt"
            with open(path, "w", encoding="utf-8") as f:
                f.write(output.intro_email)
            output.output_paths["email"] = str(path)

        if output.call_script:
            path = Path(output_dir) / f"{base_name}_CallScript.md"
            with open(path, "w", encoding="utf-8") as f:
                f.write(output.call_script)
            output.output_paths["call_script"] = str(path)

        if output.talking_points:
            path = Path(output_dir) / f"{base_name}_TalkingPoints.md"
            with open(path, "w", encoding="utf-8") as f:
                f.write(output.talking_points)
            output.output_paths["talking_points"] = str(path)

        results.append(output)

    return results


# ============================================
# CLI INTERFACE
# ============================================

if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(
        description="Generate BD Playbooks for Hot opportunities"
    )
    parser.add_argument(
        "--input", "-i", required=True, help="Input JSON file with enriched jobs"
    )
    parser.add_argument(
        "--output", "-o", default="data/deliverables/briefings", help="Output directory"
    )
    parser.add_argument(
        "--min-score", type=int, default=80, help="Minimum BD score (default: 80)"
    )
    parser.add_argument(
        "--all-formats", action="store_true", help="Generate all output formats"
    )
    parser.add_argument(
        "--no-contacts", action="store_true", help="Skip contact lookup"
    )

    args = parser.parse_args()

    # Load jobs
    with open(args.input, "r", encoding="utf-8") as f:
        jobs = json.load(f)

    if not isinstance(jobs, list):
        jobs = [jobs]

    # Determine formats
    formats = ["full", "email", "call", "talking"] if args.all_formats else ["full"]

    # Generate playbooks
    print(f"\nGenerating playbooks for jobs with BD Score >= {args.min_score}...")

    results = generate_playbooks_batch(
        jobs,
        output_dir=args.output,
        min_score=args.min_score,
        include_contacts=not args.no_contacts,
        output_formats=formats,
    )

    print(f"\nGenerated {len(results)} playbooks:")
    for output in results:
        print(
            f"  - {output.data.job_title} ({output.data.program_name}) - Score: {output.data.bd_score}"
        )
        for fmt, path in output.output_paths.items():
            print(f"    {fmt}: {path}")

    print(f"\nPlaybooks saved to: {args.output}")
