apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pts-bd-ingress
  namespace: pts-bd
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - bd.pts-internal.com
      secretName: pts-bd-tls
  rules:
    - host: bd.pts-internal.com
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: hub-api
                port:
                  number: 8100
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dashboard
                port:
                  number: 80
