"""
BD Briefing Document Generator - Generates Business Development briefing documents.
"""

from datetime import datetime
from pathlib import Path
from typing import Dict, List
from dataclasses import dataclass, field
import sys

sys.path.insert(0, str(Path(__file__).parent.parent.parent))
from Engine3_OrgChart.scripts.contact_lookup import (
    lookup_contacts,
    format_contacts_for_briefing,
    format_contacts_json,
)


@dataclass
class BriefingData:
    job_title: str
    company: str
    location: str
    clearance: str
    description: str = ""
    program_name: str = ""
    agency: str = ""
    prime_contractor: str = ""
    match_confidence: float = 0.0
    bd_score: int = 0
    priority_tier: str = ""
    contacts: List[Dict] = field(default_factory=list)


TEMPLATE = """# BD Briefing: {job_title} - {program_name}

**Generated:** {generated_date}
**Priority Level:** {priority_tier}
**BD Score:** {bd_score}/100
**Match Confidence:** {match_confidence}%

---

## Opportunity Overview

**{company}** is hiring a **{job_title}** in **{location}** requiring **{clearance}** clearance.
This position has been mapped to the **{program_name}** program.

---

## Program Background

**Program:** {program_name}
**Customer Agency:** {agency}
**Prime Contractor:** {prime_contractor}

---

## Key Contacts

{contacts_section}

---

## Recommendations

1. Reach out to {prime_contractor} BD/capture team
2. Prepare capabilities statement for {program_name}
3. Monitor for upcoming task orders

---

*Generated by BD Automation Engine*
"""


def extract_briefing_data(job):
    mapping = job.get("_mapping", {})
    scoring = job.get("_scoring", {})
    return BriefingData(
        job_title=job.get("Job Title/Position", job.get("title", "")),
        company=job.get("Prime Contractor", job.get("company", "")),
        location=job.get("Location", job.get("location", "")),
        clearance=job.get("Security Clearance", job.get("clearance", "")),
        description=job.get("Position Overview", job.get("description", "")),
        program_name=mapping.get(
            "program_name", job.get("Matched Program", "Unmatched")
        ),
        agency=mapping.get("agency", ""),
        prime_contractor=mapping.get(
            "prime_contractor", job.get("Prime Contractor", "")
        ),
        match_confidence=mapping.get("match_confidence", 0.5),
        bd_score=scoring.get("bd_score", job.get("BD Priority Score", 50)),
        priority_tier=scoring.get("tier", job.get("Priority Tier", "Warm")),
    )


def generate_briefing(job, include_contacts=True):
    data = extract_briefing_data(job)
    if include_contacts:
        result = lookup_contacts(
            program_name=data.program_name,
            prime_contractor=data.prime_contractor or data.company,
        )
        data.contacts = format_contacts_json(result)
        contacts_section = format_contacts_for_briefing(result)
    else:
        contacts_section = "Contact lookup disabled."
    markdown = TEMPLATE.format(
        job_title=data.job_title,
        company=data.company,
        location=data.location,
        clearance=data.clearance or "Not specified",
        program_name=data.program_name,
        agency=data.agency or "DoD/IC",
        prime_contractor=data.prime_contractor or data.company,
        match_confidence=int(data.match_confidence * 100),
        bd_score=data.bd_score,
        priority_tier=data.priority_tier,
        generated_date=datetime.now().strftime("%Y-%m-%d %H:%M"),
        contacts_section=contacts_section,
    )
    return {
        "markdown": markdown,
        "data": data,
        "generated_at": datetime.now().isoformat(),
    }


def generate_briefings_batch(
    jobs, output_dir="outputs/BD_Briefings", min_score=0, include_contacts=True
):
    Path(output_dir).mkdir(parents=True, exist_ok=True)
    results = []
    for job in jobs:
        score = job.get("_scoring", {}).get("bd_score", 50)
        if score < min_score:
            continue
        result = generate_briefing(job, include_contacts)
        title = job.get("Job Title/Position", "Unknown")[:40]
        program = job.get("_mapping", {}).get("program_name", "Unmatched")[:30]
        safe = lambda s: "".join(c for c in s if c.isalnum() or c in " -_")
        filename = f"{safe(program)}_{safe(title)}_Briefing.md"
        filepath = Path(output_dir) / filename
        with open(filepath, "w", encoding="utf-8") as f:
            f.write(result["markdown"])
        result["output_path"] = str(filepath)
        results.append(result)
    return results
