services:
  neo4j:
    image: neo4j:5.26.0
    environment:
      NEO4J_AUTH: neo4j/pts_bd_2026
      NEO4J_PLUGINS: '["apoc"]'
      NEO4J_server_memory_heap_max__size: 2G
      NEO4J_server_memory_pagecache_size: 1G
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data

volumes:
  neo4j_data:
